const path = require("path");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { ModuleFederationPlugin } = require("webpack").container;

module.exports = {
  entry: "./src/image-caption.js",
  output: {
    filename: "bundle.[contenthash].js",
    path: path.resolve(__dirname, "./dist"),
    // public path is where the other apps can find remoteEntry.js file for this mfe
    publicPath: "http://localhost:9003/",
  },
  mode: "development",
  devServer: {
    port: 9003,
    static: {
      directory: path.resolve(__dirname, "./dist"),
    },
    devMiddleware: {
      index: "image-caption.html",
      writeToDisk: true,
    },
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/env"],
            plugins: ["@babel/plugin-proposal-class-properties"],
          },
        },
      },

      {
        test: /\.scss$/,
        use: ["style-loader", "css-loader", "sass-loader"],
      },
    ],
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      filename: "image-caption.html",
      title: "Image Caption",
      description: "Image Caption",
    }),
    new ModuleFederationPlugin({
        // name from which this app will be used by other apps, this is mini app for eg import {} from "HelloWorldApp"
        name: "ImageCaptionApp",
        // filename is name of file generated by webpack, where all the exposed modules from this app will be added into, so as to be used by other apps
        filename: "remoteEntry.js",
        // exposes is only for mini apps, that contains the modules to be used by other apps
        exposes: {
          "./ImageCaptionComponent": "./src/image-caption.js",
        },

    })
  ],
};
