const path = require("path");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { ModuleFederationPlugin } = require("webpack").container;

module.exports = {
  entry: "./src/hello-world.js",
  output: {
    filename: "bundle.[contenthash].js",
    path: path.resolve(__dirname, "./dist"),
    publicPath: "http://localhost:9001/",
  },
  mode: "production",
  optimization: {
    splitChunks: {
      chunks: "all",
      minSize: 10000,
      automaticNameDelimiter: "_",
    },
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"],
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/env"],
            plugins: ["@babel/plugin-proposal-class-properties"],
          },
        },
      },
      {
        test: /\.hbs$/,
        use: ["handlebars-loader"],
      },
    ],
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: "styles.[contenthash].css",
    }),
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      filename: "hello-world.html",
      title: "Hello world",
      description: "Hello world",
      template: "src/page-template.hbs",
    }),
    new ModuleFederationPlugin({
      // name from which this app will be used by other apps
      name: "HelloWorldApp",
      // filename is name of file generated by webpack, where all the exposed modules from this app will be added into, so as to be used by other apps
      filename: "remoteEntry.js",
      // exposes is only for mini apps, that contains the modules to be used by other apps
      exposes: {
        // HelloWorld is the name of module used to access this file ./src/hello-world.js in other apps
        "./HelloWorldButton": './src/components/hello-world-button/hello-world-button.js',
        './HelloWorldPage': './src/components/hello-page/hello-page.js'
      },
    }),
  ],
};
