const path = require("path");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { ModuleFederationPlugin } = require("webpack").container;

module.exports = {
  entry: "./src/kiwi.js",
  output: {
    filename: "bundle.[contenthash].js",
    path: path.resolve(__dirname, "./dist"),
    // public path is where the other apps can find remoteEntry.js file for this mfe
    publicPath: "http://localhost:9002/",
  },
  mode: "development",
  devServer: {
    port: 9002,
    static: {
      directory: path.resolve(__dirname, "./dist"),
    },
    devMiddleware: {
      index: "kiwi.html",
      writeToDisk: true,
    },
  },
  module: {
    rules: [
      {
        test: /\.(png|jpg)$/,
        type: "asset",
        parser: {
          dataUrlCondition: {
            maxSize: 3 * 1024,
          },
        },
      },
      {
        test: /\.scss$/,
        use: ["style-loader", "css-loader", "sass-loader"],
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/env"],
          },
        },
      },
      {
        test: /\.hbs$/,
        use: ["handlebars-loader"],
      },
    ],
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      filename: "kiwi.html",
      title: "Kiwi",
      description: "Kiwi",
      template: "src/page-template.hbs",
    }),
    new ModuleFederationPlugin({
        // name from which this app will be used by other apps, but this is the container app
        name: "KiwiApp",
        // filename is name of file generated by webpack, where all the exposed modules from this app will be added into, so as to be used by other apps
        filename: "remoteEntry.js",
        // this is the container app, hence it uses remotes, where we'll list all the modules exposed by other app with that exact name set in ModuleFederationPlugin of mini app
        remotes: {
            // HelloWorld is the name of app that was exported by other mini app, and after @ is the path that will be used to consume remoteEntry.js file exposed from that app
            HelloWorldApp: 'HelloWorldApp@http://localhost:9001/remoteEntry.js',
            ImageCaptionApp: 'ImageCaptionApp@http://localhost:9003/remoteEntry.js'
        },
        // this app also can use exposes object in case if this app also needs to expose modules to be consumed by other apps
        exposes: {
          './KiwiPage': './src/components/kiwi-page/kiwi-page.js' 
        }
    })
  ],
};
